In [13]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [14]:
###
### THIS FILE FINDS THE TOP WINNINGS PER POKIE IN LATEST MONTH
### WIN/MACHINE AND MACHINE% CALCULATED IN EXCEL IN OCT18 EXAMPLE
### DATA: https://data.qld.gov.au/dataset/total-queensland-club-gaming-machine-data

In [17]:
df1 = pd.read_csv("20181115_OLGR_LGA-EGM-data.csv")

IOError: File 20181115_OLGR_LGA-EGM-data.csv does not exist

In [ ]:
df1

In [10]:
df2 = df1[df1['Approved Sites'] > 6]

NameError: name 'df1' is not defined

In [11]:
df_monthly = df2[df2['Month Year'] == 'Oct-18']

NameError: name 'df2' is not defined

In [32]:
df_monthly

,Month Year,LGA Region,Approved Sites,Operational Sites,Approved EGMs,Operational EGMs,Metered Win,Machine %,Win/machine,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
30,Oct-18,LOGAN,37,35.0,2142,1937.0,13607184.06,90.429505,7024.875612,NaN,NaN,NaN,NaN,NaN
141,Oct-18,MORETON BAY,60,60.0,3391,3303.0,18330328.46,97.404895,5549.599897,NaN,NaN,NaN,NaN,NaN
224,Oct-18,WHITSUNDAY,18,16.0,519,421.0,2233161.12,81.117534,5304.420713,NaN,NaN,NaN,NaN,NaN
235,Oct-18,CAIRNS,40,39.0,1902,1816.0,9605598.17,95.478444,5289.426305,NaN,NaN,NaN,NaN,NaN
305,Oct-18,REDLAND,28,27.0,1328,1180.0,6030757.11,88.855422,5110.81111,NaN,NaN,NaN,NaN,NaN
306,Oct-18,IPSWICH,34,33.0,1807,1629.0,8323916.63,90.149419,5109.832185,NaN,NaN,NaN,NaN,NaN
357,Oct-18,LOCKYER VALLEY,14,14.0,221,212.0,1064307.21,95.927602,5020.317028,NaN,NaN,NaN,NaN,NaN
471,Oct-18,ROCKHAMPTON,32,30.0,1019,919.0,4436409.74,90.186457,4827.431708,NaN,NaN,NaN,NaN,NaN
543,Oct-18,DOUGLAS,8,8.0,186,178.0,841920.78,95.698925,4729.892022,NaN,NaN,NaN,NaN,NaN
813,Oct-18,LIVINGSTONE,12,11.0,297,287.0,1273017.04,96.632997,4435.599443,NaN,NaN,NaN,NaN,NaN
833,Oct-18,NOOSA,14,14.0,524,514.0,2271982.42,98.091603,4420.199261,NaN,NaN,NaN,NaN,NaN
1113,Oct-18,MACKAY,40,37.0,1732,1607.0,6748389.46,92.782910,4199.371164,NaN,NaN,NaN,NaN,NaN
1150,Oct-18,TOOWOOMBA,50,47.0,1624,1492.0,6235278.58,91.871921,4179.141139,NaN,NaN,NaN,NaN,NaN
1267,Oct-18,HINCHINBROOK,8,7.0,107,89.0,365473.32,83.177570,4106.441798,NaN,NaN,NaN,NaN,NaN
1293,Oct-18,BUNDABERG,35,34.0,1364,1155.0,4725010.67,84.677419,4090.918329,NaN,NaN,NaN,NaN,NaN
1738,Oct-18,CHARTERS TOWERS,8,8.0,130,130.0,502762.62,100.000000,3867.404769,NaN,NaN,NaN,NaN,NaN
1740,Oct-18,GYMPIE,19,19.0,392,370.0,1430712.11,94.387755,3866.789486,NaN,NaN,NaN,NaN,NaN
1770,Oct-18,BANANA,9,9.0,151,148.0,570239.08,98.013245,3852.966757,NaN,NaN,NaN,NaN,NaN
1875,Oct-18,CENTRAL HIGHLANDS,16,16.0,385,371.0,1412912.26,96.363636,3808.388841,NaN,NaN,NaN,NaN,NaN
1881,Oct-18,FRASER COAST,33,33.0,1336,1312.0,4991256.02,98.203593,3804.310991,NaN,NaN,NaN,NaN,NaN
1906,Oct-18,GLADSTONE,25,23.0,617,587.0,2228279.49,95.137763,3796.046831,NaN,NaN,NaN,NaN,NaN
2336,Oct-18,BURDEKIN,7,7.0,206,172.0,623407.59,83.495146,3624.462733,NaN,NaN,NaN,NaN,NaN
2727,Oct-18,ISAAC,14,14.0,299,305.0,1065755.97,102.006689,3494.281869,NaN,NaN,NaN,NaN,NaN
2902,Oct-18,MARANOA,9,9.0,174,148.0,508892.38,85.057471,3438.462027,NaN,NaN,NaN,NaN,NaN
2925,Oct-18,SOMERSET,11,9.0,134,106.0,363517.66,79.104478,3429.411887,NaN,NaN,NaN,NaN,NaN
3241,Oct-18,TOWNSVILLE,43,39.0,1983,1748.0,8613336.04,88.149269,4927.53778,NaN,NaN,NaN,NaN,NaN
3539,Oct-18,GOLD COAST,129,124.0,5941,5678.0,28949814.62,95.573136,5098.593628,NaN,NaN,NaN,NaN,NaN
3701,Oct-18,SOUTH BURNETT,17,17.0,338,331.0,1052953.89,97.928994,3181.129577,NaN,NaN,NaN,NaN,NaN
3760,Oct-18,GOONDIWINDI,9,9.0,155,147.0,464866.00,94.838710,3162.353741,NaN,NaN,NaN,NaN,NaN
3917,Oct-18,CASSOWARY COAST,14,14.0,374,372.0,1159100.01,99.465241,3115.860242,NaN,NaN,NaN,NaN,NaN
3960,Oct-18,BRISBANE,183,175.0,8867,8263.0,45474787.84,93.188226,5503.423435,NaN,NaN,NaN,NaN,NaN
4045,Oct-18,WESTERN DOWNS,24,23.0,377,339.0,1043704.18,89.920424,3078.773392,NaN,NaN,NaN,NaN,NaN
4755,Oct-18,SUNSHINE COAST,68,67.0,2999,2956.0,12946388.18,98.566189,4379.698302,NaN,NaN,NaN,NaN,NaN
4823,Oct-18,SCENIC RIM,17,17.0,229,220.0,622238.45,96.069869,2828.356591,NaN,NaN,NaN,NaN,NaN
5124,Oct-18,SOUTHERN DOWNS,14,13.0,395,358.0,976967.59,90.632911,2728.959749,NaN,NaN,NaN,NaN,NaN
5390,Oct-18,NORTH BURNETT,8,8.0,83,83.0,218130.36,100.000000,2628.076627,NaN,NaN,NaN,NaN,NaN

In [33]:
    df_monthly.sort_values('Win/machine',ascending=False)

,Month Year,LGA Region,Approved Sites,Operational Sites,Approved EGMs,Operational EGMs,Metered Win,Machine %,Win/machine,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
30,Oct-18,LOGAN,37,35.0,2142,1937.0,13607184.06,90.429505,7024.875612,NaN,NaN,NaN,NaN,NaN
141,Oct-18,MORETON BAY,60,60.0,3391,3303.0,18330328.46,97.404895,5549.599897,NaN,NaN,NaN,NaN,NaN
3960,Oct-18,BRISBANE,183,175.0,8867,8263.0,45474787.84,93.188226,5503.423435,NaN,NaN,NaN,NaN,NaN
224,Oct-18,WHITSUNDAY,18,16.0,519,421.0,2233161.12,81.117534,5304.420713,NaN,NaN,NaN,NaN,NaN
235,Oct-18,CAIRNS,40,39.0,1902,1816.0,9605598.17,95.478444,5289.426305,NaN,NaN,NaN,NaN,NaN
305,Oct-18,REDLAND,28,27.0,1328,1180.0,6030757.11,88.855422,5110.81111,NaN,NaN,NaN,NaN,NaN
306,Oct-18,IPSWICH,34,33.0,1807,1629.0,8323916.63,90.149419,5109.832185,NaN,NaN,NaN,NaN,NaN
3539,Oct-18,GOLD COAST,129,124.0,5941,5678.0,28949814.62,95.573136,5098.593628,NaN,NaN,NaN,NaN,NaN
357,Oct-18,LOCKYER VALLEY,14,14.0,221,212.0,1064307.21,95.927602,5020.317028,NaN,NaN,NaN,NaN,NaN
3241,Oct-18,TOWNSVILLE,43,39.0,1983,1748.0,8613336.04,88.149269,4927.53778,NaN,NaN,NaN,NaN,NaN
471,Oct-18,ROCKHAMPTON,32,30.0,1019,919.0,4436409.74,90.186457,4827.431708,NaN,NaN,NaN,NaN,NaN
543,Oct-18,DOUGLAS,8,8.0,186,178.0,841920.78,95.698925,4729.892022,NaN,NaN,NaN,NaN,NaN
813,Oct-18,LIVINGSTONE,12,11.0,297,287.0,1273017.04,96.632997,4435.599443,NaN,NaN,NaN,NaN,NaN
833,Oct-18,NOOSA,14,14.0,524,514.0,2271982.42,98.091603,4420.199261,NaN,NaN,NaN,NaN,NaN
4755,Oct-18,SUNSHINE COAST,68,67.0,2999,2956.0,12946388.18,98.566189,4379.698302,NaN,NaN,NaN,NaN,NaN
1113,Oct-18,MACKAY,40,37.0,1732,1607.0,6748389.46,92.782910,4199.371164,NaN,NaN,NaN,NaN,NaN
1150,Oct-18,TOOWOOMBA,50,47.0,1624,1492.0,6235278.58,91.871921,4179.141139,NaN,NaN,NaN,NaN,NaN
1267,Oct-18,HINCHINBROOK,8,7.0,107,89.0,365473.32,83.177570,4106.441798,NaN,NaN,NaN,NaN,NaN
1293,Oct-18,BUNDABERG,35,34.0,1364,1155.0,4725010.67,84.677419,4090.918329,NaN,NaN,NaN,NaN,NaN
1738,Oct-18,CHARTERS TOWERS,8,8.0,130,130.0,502762.62,100.000000,3867.404769,NaN,NaN,NaN,NaN,NaN
1740,Oct-18,GYMPIE,19,19.0,392,370.0,1430712.11,94.387755,3866.789486,NaN,NaN,NaN,NaN,NaN
1770,Oct-18,BANANA,9,9.0,151,148.0,570239.08,98.013245,3852.966757,NaN,NaN,NaN,NaN,NaN
1875,Oct-18,CENTRAL HIGHLANDS,16,16.0,385,371.0,1412912.26,96.363636,3808.388841,NaN,NaN,NaN,NaN,NaN
1881,Oct-18,FRASER COAST,33,33.0,1336,1312.0,4991256.02,98.203593,3804.310991,NaN,NaN,NaN,NaN,NaN
1906,Oct-18,GLADSTONE,25,23.0,617,587.0,2228279.49,95.137763,3796.046831,NaN,NaN,NaN,NaN,NaN
2336,Oct-18,BURDEKIN,7,7.0,206,172.0,623407.59,83.495146,3624.462733,NaN,NaN,NaN,NaN,NaN
2727,Oct-18,ISAAC,14,14.0,299,305.0,1065755.97,102.006689,3494.281869,NaN,NaN,NaN,NaN,NaN
2902,Oct-18,MARANOA,9,9.0,174,148.0,508892.38,85.057471,3438.462027,NaN,NaN,NaN,NaN,NaN
2925,Oct-18,SOMERSET,11,9.0,134,106.0,363517.66,79.104478,3429.411887,NaN,NaN,NaN,NaN,NaN
3701,Oct-18,SOUTH BURNETT,17,17.0,338,331.0,1052953.89,97.928994,3181.129577,NaN,NaN,NaN,NaN,NaN
3760,Oct-18,GOONDIWINDI,9,9.0,155,147.0,464866.00,94.838710,3162.353741,NaN,NaN,NaN,NaN,NaN
3917,Oct-18,CASSOWARY COAST,14,14.0,374,372.0,1159100.01,99.465241,3115.860242,NaN,NaN,NaN,NaN,NaN
4045,Oct-18,WESTERN DOWNS,24,23.0,377,339.0,1043704.18,89.920424,3078.773392,NaN,NaN,NaN,NaN,NaN
4823,Oct-18,SCENIC RIM,17,17.0,229,220.0,622238.45,96.069869,2828.356591,NaN,NaN,NaN,NaN,NaN
5124,Oct-18,SOUTHERN DOWNS,14,13.0,395,358.0,976967.59,90.632911,2728.959749,NaN,NaN,NaN,NaN,NaN
5390,Oct-18,NORTH BURNETT,8,8.0,83,83.0,218130.36,100.000000,2628.076627,NaN,NaN,NaN,NaN,NaN

In [34]:
df_monthly.sort_values('Metered Win',ascending=False)

,Month Year,LGA Region,Approved Sites,Operational Sites,Approved EGMs,Operational EGMs,Metered Win,Machine %,Win/machine,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3960,Oct-18,BRISBANE,183,175.0,8867,8263.0,45474787.84,93.188226,5503.423435,NaN,NaN,NaN,NaN,NaN
3539,Oct-18,GOLD COAST,129,124.0,5941,5678.0,28949814.62,95.573136,5098.593628,NaN,NaN,NaN,NaN,NaN
141,Oct-18,MORETON BAY,60,60.0,3391,3303.0,18330328.46,97.404895,5549.599897,NaN,NaN,NaN,NaN,NaN
30,Oct-18,LOGAN,37,35.0,2142,1937.0,13607184.06,90.429505,7024.875612,NaN,NaN,NaN,NaN,NaN
4755,Oct-18,SUNSHINE COAST,68,67.0,2999,2956.0,12946388.18,98.566189,4379.698302,NaN,NaN,NaN,NaN,NaN
235,Oct-18,CAIRNS,40,39.0,1902,1816.0,9605598.17,95.478444,5289.426305,NaN,NaN,NaN,NaN,NaN
3241,Oct-18,TOWNSVILLE,43,39.0,1983,1748.0,8613336.04,88.149269,4927.53778,NaN,NaN,NaN,NaN,NaN
306,Oct-18,IPSWICH,34,33.0,1807,1629.0,8323916.63,90.149419,5109.832185,NaN,NaN,NaN,NaN,NaN
1113,Oct-18,MACKAY,40,37.0,1732,1607.0,6748389.46,92.782910,4199.371164,NaN,NaN,NaN,NaN,NaN
1150,Oct-18,TOOWOOMBA,50,47.0,1624,1492.0,6235278.58,91.871921,4179.141139,NaN,NaN,NaN,NaN,NaN
305,Oct-18,REDLAND,28,27.0,1328,1180.0,6030757.11,88.855422,5110.81111,NaN,NaN,NaN,NaN,NaN
1881,Oct-18,FRASER COAST,33,33.0,1336,1312.0,4991256.02,98.203593,3804.310991,NaN,NaN,NaN,NaN,NaN
1293,Oct-18,BUNDABERG,35,34.0,1364,1155.0,4725010.67,84.677419,4090.918329,NaN,NaN,NaN,NaN,NaN
471,Oct-18,ROCKHAMPTON,32,30.0,1019,919.0,4436409.74,90.186457,4827.431708,NaN,NaN,NaN,NaN,NaN
833,Oct-18,NOOSA,14,14.0,524,514.0,2271982.42,98.091603,4420.199261,NaN,NaN,NaN,NaN,NaN
224,Oct-18,WHITSUNDAY,18,16.0,519,421.0,2233161.12,81.117534,5304.420713,NaN,NaN,NaN,NaN,NaN
1906,Oct-18,GLADSTONE,25,23.0,617,587.0,2228279.49,95.137763,3796.046831,NaN,NaN,NaN,NaN,NaN
1740,Oct-18,GYMPIE,19,19.0,392,370.0,1430712.11,94.387755,3866.789486,NaN,NaN,NaN,NaN,NaN
1875,Oct-18,CENTRAL HIGHLANDS,16,16.0,385,371.0,1412912.26,96.363636,3808.388841,NaN,NaN,NaN,NaN,NaN
813,Oct-18,LIVINGSTONE,12,11.0,297,287.0,1273017.04,96.632997,4435.599443,NaN,NaN,NaN,NaN,NaN
3917,Oct-18,CASSOWARY COAST,14,14.0,374,372.0,1159100.01,99.465241,3115.860242,NaN,NaN,NaN,NaN,NaN
2727,Oct-18,ISAAC,14,14.0,299,305.0,1065755.97,102.006689,3494.281869,NaN,NaN,NaN,NaN,NaN
357,Oct-18,LOCKYER VALLEY,14,14.0,221,212.0,1064307.21,95.927602,5020.317028,NaN,NaN,NaN,NaN,NaN
3701,Oct-18,SOUTH BURNETT,17,17.0,338,331.0,1052953.89,97.928994,3181.129577,NaN,NaN,NaN,NaN,NaN
4045,Oct-18,WESTERN DOWNS,24,23.0,377,339.0,1043704.18,89.920424,3078.773392,NaN,NaN,NaN,NaN,NaN
5124,Oct-18,SOUTHERN DOWNS,14,13.0,395,358.0,976967.59,90.632911,2728.959749,NaN,NaN,NaN,NaN,NaN
543,Oct-18,DOUGLAS,8,8.0,186,178.0,841920.78,95.698925,4729.892022,NaN,NaN,NaN,NaN,NaN
2336,Oct-18,BURDEKIN,7,7.0,206,172.0,623407.59,83.495146,3624.462733,NaN,NaN,NaN,NaN,NaN
4823,Oct-18,SCENIC RIM,17,17.0,229,220.0,622238.45,96.069869,2828.356591,NaN,NaN,NaN,NaN,NaN
1770,Oct-18,BANANA,9,9.0,151,148.0,570239.08,98.013245,3852.966757,NaN,NaN,NaN,NaN,NaN
2902,Oct-18,MARANOA,9,9.0,174,148.0,508892.38,85.057471,3438.462027,NaN,NaN,NaN,NaN,NaN
1738,Oct-18,CHARTERS TOWERS,8,8.0,130,130.0,502762.62,100.000000,3867.404769,NaN,NaN,NaN,NaN,NaN
3760,Oct-18,GOONDIWINDI,9,9.0,155,147.0,464866.00,94.838710,3162.353741,NaN,NaN,NaN,NaN,NaN
1267,Oct-18,HINCHINBROOK,8,7.0,107,89.0,365473.32,83.177570,4106.441798,NaN,NaN,NaN,NaN,NaN
2925,Oct-18,SOMERSET,11,9.0,134,106.0,363517.66,79.104478,3429.411887,NaN,NaN,NaN,NaN,NaN
5390,Oct-18,NORTH BURNETT,8,8.0,83,83.0,218130.36,100.000000,2628.076627,NaN,NaN,NaN,NaN,NaN